export const PROMISE = 'PROMISE';
export const LOADING_PHOTOS = 'LOADING_PHOTOS';
export const LOADED_PHOTOS = 'LOADED_PHOTOS';
export const LOAD_FAILURE_PHOTOS = 'LOAD_FAILURE_PHOTOS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SAVE_NEW_PAGE = 'SAVE_NEW_PAGE';
export const ADD_COMMENT = 'ADD_COMMENT';

