export const GET_PHOTOS = 'GET_PHOTOS';
export const LOADING_PHOTOS = 'LOADING_PHOTOS';
export const LOADED_PHOTOS = 'LOADED_PHOTOS';
export const LOAD_FAILURE_PHOTOS = 'LOAD_FAILURE_PHOTOS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SAVE_NEW_PAGE = 'SAVE_NEW_PAGE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_STORE = 'ADD_COMMENT_STORE';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const GET_IMAGE_URL = 'GET_IMAGE_URL';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const ADD_PHOTO = 'ADD_PHOTO';
export const DELETE_PHOTO = 'DELETE_PHOTO';
export const DELETE_STORE_PHOTO = 'DELETE_STORE_PHOTO';

